StudentNotes/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StudentNotes.Models
{
    public class Student
    {
        public int Id { get; set; }

        [Required] public string Name { get; set; }

        [Required] public string Address { get; set; }

        [Required] public string Phone { get; set; }

        public List<Note> Notes { get; set; }
    }
}

StudentNotes/Controllers/Api/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Configuration;
using System.Web.Http;
using AutoMapper;
using StudentNotes.Dtos;
using StudentNotes.Models;

namespace StudentNotes.Controllers.Api
{
    public class StudentController : ApiController
    {

        private ApplicationDbContext _context;

        public StudentController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        // GET   /api/student
        public IHttpActionResult GetStudents()
        {
            var studentDto = _context.Students.ToList().Select(Mapper.Map<Student, StudentDto>);

            return Ok(studentDto);
        }


        // GET   /api/student/id
        public IHttpActionResult GetStudent(int id)
        {
            var student = _context.Students.SingleOrDefault(s => s.Id == id);

            if (student == null)
                return NotFound();

            return Ok(Mapper.Map<Student, StudentDto>(student));


        }

        // POST    /api/student
        [HttpPost]
        public IHttpActionResult CreateStudent(StudentDto studentDto)
        {

            if (!ModelState.IsValid)
                return BadRequest();

            var student = Mapper.Map<StudentDto, Student>(studentDto);
            _context.Students.Add(student);
            _context.SaveChanges();

            studentDto.Id = student.Id;

            return Created(new Uri(Request.RequestUri + "/" + student.Id), studentDto);

        }


        // PUT     /api/student/id
        [HttpPut]
        public IHttpActionResult UpdateStudent(int id, StudentDto studentDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var studentInDb = _context.Students.SingleOrDefault(s => s.Id == id);

            if (studentInDb == null)
                return NotFound();

            Mapper.Map<StudentDto, Student>(studentDto, studentInDb);
            

            _context.SaveChanges();

            return Ok();
        }


        // DELETE     /api/student/id
        [HttpDelete]
        public IHttpActionResult DeleteStudent(int id)
        {
            var studentInDb = _context.Students.SingleOrDefault(s => s.Id == id);

            if (studentInDb == null)
                return NotFound();

            _context.Students.Remove(studentInDb);
            _context.SaveChanges();

            return Ok();

        }
    }
}

StudentNotes/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using StudentNotes.Models;

namespace StudentNotes.Controllers
{
    public class NoteController : Controller
    {
        private ApplicationDbContext _context;

        public NoteController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        public ActionResult Details(int id)
        {
            var note = _context.Notes.SingleOrDefault(n => n.Id == id);

            return View(note);
        }

        public ActionResult Save(Note note)
        {
            if (note.Id == 0)
            {
                note.DateAdded = DateTime.Now;
                _context.Notes.Add(note);
            }

            else
            {
                var noteInDb = _context.Notes.Single(n => n.Id == note.Id);
                noteInDb.Name = note.Name;
                noteInDb.ProgressRating = note.ProgressRating;
                noteInDb.ExtraNote = note.ExtraNote;
                noteInDb.StudentId = note.StudentId;
                noteInDb.DateAdded = DateTime.Now;
            }

            _context.SaveChanges();

            return RedirectToAction("Details" + "/" + note.StudentId, "Student");
        }

        public ActionResult New(int studentId)
        {
            return View("Details");
        }


        public ActionResult Delete(int id)
        {
            var noteInDb = _context.Notes.Single(n => n.Id == id);

            var noteInDbStudentId = noteInDb.StudentId;

            _context.Notes.Remove(noteInDb);
            _context.SaveChanges();

            return RedirectToAction("Details" + "/" + noteInDbStudentId, "Student");
        }
    }
}

StudentNotes/Controllers/StudentController.cs
using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentNotes.Models;

namespace StudentNotes.Controllers
{
    public class StudentController : Controller
    {
        private ApplicationDbContext _context;

        public StudentController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        public ActionResult Index()
        {
            var student = _context.Students.ToList();
    
            return View(student);
        }


        public ActionResult Details(int id)
        {
            var student = _context.Students
                .Include(s => s.Notes)
                .SingleOrDefault(s => s.Id == id);

            if (student == null)
                return HttpNotFound();

            return View(student);
        }


        public ActionResult New()
        {
            return View("New");
        }


        public ActionResult Delete(int studentId)
        {
            var studentInDb = _context.Students.Single(s => s.Id == studentId);
            var studentNotesInDb = _context.Notes.ToList().Where(n => n.StudentId == studentInDb.Id);

            foreach (var note in studentNotesInDb)
            {
                _context.Notes.Remove(note);
            }

            _context.Students.Remove(studentInDb);
            _context.SaveChanges();

            return RedirectToAction("Index", "Student");
        }


        public ActionResult Save(Student student)
        {
            if (student.Id == 0)
            {
                _context.Students.Add(student);
            }

            else
            {
                var studentInDb = _context.Students.Single(s => s.Id == student.Id);
                studentInDb.Name = student.Name;
                studentInDb.Address = student.Address;
                studentInDb.Phone = student.Phone;
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Student");
        }

        public ActionResult Edit(int studentId)
        {
            var studentInDb = _context.Students.Single(s => s.Id == studentId);

            return View(studentInDb);
        }
    }
}

StudentNotes/Views/Student/Details.cshtml
@model StudentNotes.Models.Student

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<p>Address: @Model.Address</p>
<p>Phone: @Model.Phone</p>


@Html.ActionLink("New Note", "New", "Note", new {studentId = Model.Id}, new {@class = "btn btn-primary"})
@Html.ActionLink("Edit Student", "Edit", "Student", new {studentId = Model.Id}, new {@class = "btn btn-primary"})
@Html.ActionLink("DELETE STUDENT", "Delete", "Student", new {studentId = Model.Id}, new {@class = "btn btn-primary"})

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Note</th>
        <th>Progress Rating</th>
        <th>Extra Note</th>
        <th>Date Added</th>
    </tr>

    </thead>
    <tbody>
    
    @if (!Model.Notes.Any())
    {
        <p>You don't have any notes for this student yet.</p>
    }

    @foreach (var notes in Model.Notes)
    {
        <tr>
            <td>@Html.ActionLink(notes.Name, "Details", "Note", new {id = notes.Id, studentId = notes.StudentId}, null)</td>
            <td>@notes.ProgressRating</td>
            <td>@notes.ExtraNote</td>
            <td>@notes.DateAdded.ToShortDateString()</td>
        </tr>
    }


    </tbody>


</table>

StudentNotes/Views/Student/Edit.cshtml
@model StudentNotes.Models.Student
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Save", "Student"))
{
    <div class="form-group">
        @Html.LabelFor(n => n.Name)
        @Html.TextAreaFor(n => n.Name, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.Address)
        @Html.TextAreaFor(n => n.Address, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.Phone)
        @Html.TextAreaFor(n => n.Phone, new {@class = "form-control"})
    </div>
    @Html.HiddenFor(n => Model.Id)

    <button type="submit" class="btn btn-primary">Save</button>
}

StudentNotes/Views/Student/Index.cshtml
@model IEnumerable<StudentNotes.Models.Student>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Students</h2>
@Html.ActionLink("New Student", "New", "Student", new {}, new {@class = "btn btn-primary"})

@if (!Model.Any())
{
    <p>You don't have any students yet.</p>
}

else
{
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Student</th>
            <th>Address</th>
            <th>Phone Number</th>
        </tr>
        </thead>

        <tbody>

        @foreach (var student in Model)
        {
            <tr>
                <td>@Html.ActionLink(student.Name, "Details", "Student", new {id = student.Id}, null)</td>
                <td>@student.Address</td>
                <td>@student.Phone</td>
            </tr>
        }

        </tbody>

    </table>
}

StudentNotes/Views/Student/New.cshtml
@model StudentNotes.Models.Student

@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <h2>New Student</h2>
}
else
{
    <h2>Student Details</h2>
}



@using (Html.BeginForm("Save", "Student"))
{
    <div class="form-group">
        @Html.LabelFor(n => n.Name)
        @Html.TextAreaFor(n => n.Name, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.Address)
        @Html.TextAreaFor(n => n.Address, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.Phone)
        @Html.TextAreaFor(n => n.Phone, new {@class = "form-control"})
    </div>
    @Html.HiddenFor(n => Model.Id)

    <button type="submit" class="btn btn-primary">Save</button>
}